decentralized-identity/didwebvh

- index.html
- spec/example.md
- spec/specification.md
- **Added examples, cleanups**
> Added examples, cleanups

- spec/abstract.md
- spec/overview.md
> Move feature list from overview to abstract

- README.md
- spec/definitions.md
- spec/example.md
- spec/overview.md
- spec/specification.md
- **Update Readme**
- **Remove spec-up from Readme**
- **Typo**
- **Typo**
- **Updates from the 20240410 meeting to the spec**
> Updates from the 20240410 meeting to the spec

- spec/abstract.md
- spec/definitions.md
- spec/implementors_guide.md
- spec/overview.md
- spec/specification.md
> Feedback cleanup and add links to implementations

- README.md
> Add python implementation

- spec/implementors_guide.md
> Reference Python implementation

- spec/example.md
No content or version changes -- just updates to the examples and the surrounding text.
> Update examples to v3

- spec/overview.md
Minor changes and rephrased sentences to support readability and consistency across the spec. Updates only applied on a text-level, no changes to any concepts, methods etc..
Signed-off-by: martipos <176692840+martipos@users.noreply.github.com>
> Clarification of content in the overview

- spec/abstract.md
- spec/definitions.md
- spec/header.md
re-do of RP#84 including addressed corresponding feedback. New RP was needed due to dco troubles - ignore the original RP#84
> Clarifications of did:tdw features (abstract) and definitions - V2

- spec/specification.md
Consolidated information where it made sense, deleted redundant information and referenced to complementary information in the specification.
Signed-off-by: martipos <176692840+martipos@users.noreply.github.com>
> Clarification of DID creation (registration)

- README.md
- spec/header.md
- spec/implementors_guide.md
- spec/overview.md
> Update link to spec, add editor and implementation link

- agenda.md
- **General updates to the agenda page and adding the Sept 12 meeting**
- **Additional cleanup, use of vscode tools for TOC generation**
- **Cleanup HackMD link -- remove impression of sync=ing**
> Tweak to agenda to fix HackMD link

- agenda.md
- **General updates to the agenda page and adding the Sept 12 meeting**
- **Additional cleanup, use of vscode tools for TOC generation**
- **Cleanup HackMD link -- remove impression of sync=ing**
- **Agenda Update after 20240812 Meeting**
> Agenda Update after 20240812 Meeting

- agenda.md
> Agenda after 20241024 Meeting

- agenda.md
> Agenda updated after the 2024.11.07 Work Item Meeting

- spec/security_and_privacy.md
Text pulled from [here](https://w3c-ccg.github.io/did-method-web/#cross-origin-resource-sharing-cors-policy-considerations)
> Add CORS details

- spec/abstract.md
- specs.json
Left a typo in the specs.json file that I didn't test (obvs) before submitting. Never make last second changes to PRs! :-)
> Fix typos from the previous PR

- README.md
- package.json
- spec-v0.3/header.md
- spec-v0.4/header.md
- spec/header.md
- specs.json
> Changes after the repo renaming

- spec/abstract.md
- spec/definitions.md
- spec/specification.md
- spec/version.md
There were a number of dangling definitions and unresolved references I have cleaned up
> Fix up definitions and references

- spec/overview.md
No description needed, it was broken and updated with the right link
> update webpage link

- README.md
- spec-v0.3/header.md
- spec-v0.4/header.md
- spec/header.md
> Try 2 to fix the cross version links
